### ISSUE TITLE
Set up repo with GPT explorations

### ISSUE THREAD

**Issue by markwhiting** [Watts-Lab/atlas#10]
Setting up the analysis script: @krystalgong

- [ ] Create folder `GPT exploration`
- [ ] Add code for performing systematic requests
- [ ] Make code run based on parameters that include a questions file and a PDF file. Questions file should be CSV close to the structure we got from Linnea (i.e., `name`, `question`, other stuff, `answer_options` (e.g., `["Yes", "No"]`)). We should assume the PDF file is a paper. 

```python
answers = answer_questions_for_paper(questions.csv, paper.pdf)
```

- [ ] Provide a structured response that has format something like (where each question name comes from a name column in the `questions.csv`: 

```python
answers = {
  question_name_1: "question answer 1",
  question_name_2: "question answer 2"
}
```

- [ ] @krystalgong — PR the setup as listed above (request a review from @markwhiting when you do and I'll try to look ASAP)
- [ ] @fanxia0926 — start trialing with the above in order to explore agent driven methods for refining prompts. Try things like feedback from ground truth on other papers, ground truth on other questions, and in a multi level design where different agent components may have different feedback frames. Of course, there are many other options, so feel free to try a lot of different approaches. 
- [ ] @fanxia0926 — branch off @krystalgong's work and PR to main.

**Comment by krystalgong** [comment]
Currently, I don't have access to push to the main folder so I fork one and upload my code there.

**Comment by markwhiting** [comment]
Closed as we are starting to think about some of these tasks a bit differently.
