### ISSUE TITLE
DB design

### ISSUE THREAD

**Issue by markwhiting** [Watts-Lab/atlas#25]
Main tables:

1. `documents` - MD text + paper pdf + SI pdfs etc.
2. `features` - specifying how they are answered and their scope of abstraction
3. `scopes` - scopes of abstraction, e.g., experiment, condition etc.
4. `projects` - a collection of features
5. `ratings` - a value for a document for a feature
6. `users` - (need not think about this too much for now)

**Comment by amirrr** [comment]
![image](https://github.com/Watts-Lab/atlas/assets/6696894/1cb86428-e318-451b-aa62-8b888b1a892e)
