### ISSUE TITLE
Table for displaying GPT feature extraction results

### ISSUE THREAD

**Issue by amirrr** [Watts-Lab/atlas#36]
#### Description
The goal is to have a table that displays the values for features extracted by GPT. We want to have column for each feature with the results from GPT json call. The results will be served via either socket/http api call from the backend endpoint `/api/run`. The table should give the user the ability to sort each column by their values. If the user wants to add a feature to their list they should be able to click a + sign on the right side of the table choose a feature from a dropdown list taken from endpoint `GET /api/features`. Also we would like to assign a accuracy score to each answer taken from GPT which is served with the answer from the api call. So a cell inside the table should be able to adjust its color between red and green based on a score from 0.0 to 1.0.

#### User Stories / Use Cases
- **User Story 1:** As a researcher, I want to be able to get conditons.name and conditions.type on the paper I have selected.
- **User Story 2:** As a researcher, I would like to be able to see the available features implement on the platform a select one or more to be displayed on the paper I am studying.

#### Acceptance Criteria
- [ ] Rows of table displayed from a json provided by backend.
- [ ] Cell colors for cells with answers which have an accuracy score and those which don't no color
- [ ] Dropdown menu for selecting a feature (adding a column to the table from a dropdown of available features)
- [ ] Hot-loading for features as they come in from the backend or some indication that the request is being processed

#### Requirements
- Use DaisyUI for component visuals
- The component should be tested with Cypress component testing (if more comfortable with other libraries playwright, etc.)

**Tips:**
Create a component ResultTable.tsx (You can have dropdown as a seperate component) > put the hooks under `hooks/` with backend calls and keep them in a way so the url can be changed.

#### Design and Mockups
![image](https://github.com/Watts-Lab/atlas/assets/6696894/71316d11-73e4-4ad4-bd30-994752c534d0)

**Comment by Jaishree2310** [comment]
Hi @amirrr, I am interested in solving this issue. Can you please assign this to me? 
Thanks!

**Comment by amirrr** [comment]
> Hi @amirrr, I am interested in solving this issue. Can you please assign this to me? Thanks!

Hi @Jaishree2310, sure you can go ahead and start. Create a fork of the repo and checkout into a branch with issue id. When you are ready go ahead and create a pull request and we will add it to the repo.
