### ISSUE TITLE
Convert pdf to markdown 

### ISSUE THREAD

**Issue by amirrr** [Watts-Lab/atlas#38]
One helpful way of processing the pdf documents of scientific articles is to extract the text from them and run the converted document through GPT. This depending on the type of pdf can result in cheaper and more accurate results since you don't need to pay for file storage on OpenAI and text is cheaper to process. To convert the data, there are a couple of tools of which [Marker](https://github.com/VikParuchuri/marker) seems to be the best. 

To integrate marker as part of our pipeline, one of the ways is keep it as a service that runs as a batch job on files stored on S3 bucket. For this we can have a S3 bucket where upon a file upload would trigger a AWS Lambda function to trigger [AWS Batch Job](https://docs.aws.amazon.com/batch/latest/userguide/getting-started-fargate.html).

Steps:

1. Create an S3 Bucket for files served by users.
2. AWS Lambda function that triggers when there is a new file
3. AWS Batch job from a container (Container with Marker and Pytorch) triggered by Lambda
4. Saving the file back to S3 and forwarding the meta data to backend

Ideally all of this setup should be deployed with [Terraform](https://www.terraform.io/) script.

**Comment by markwhiting** [comment]
If we prioritize performance over budget, is markdown as textual context better than having PDFs in the assistance API?

**Comment by markwhiting** [comment]
In checking that, we should try situations where a key detail is in a figure and see which approach deals with it better. 

@linneagandhi — do you have any choice examples where a figure contains key information for one of your variables? I know we had talked about some cases like that but just wondering if you recall any papers that were critical instances of that issue.

**Comment by markwhiting** [comment]
I think this is done now that we are using the other pipeline, so marking complete. Please open if I'm wrong.
