### ISSUE TITLE
Save gpt reponse assigned to paper in DB

### ISSUE THREAD

**Issue by markwhiting** [Watts-Lab/atlas#55]
Save the response object from OpenAI endpoint in a MongoDB collection.
Keep token consumption and user_id separate.

**Comment by markwhiting** [comment]
Is this now done @amirrr

**Comment by amirrr** [comment]
> Is this now done [@amirrr](https://github.com/amirrr)

Yeah mostly, some small details need to be refined still. I will close this with my current PR which also covers this issue with projects

**Comment by markwhiting** [comment]
OK, thanks!
