### ISSUE TITLE
Create a task queue for OpenAI or Claude api call

### ISSUE THREAD

**Issue by amirrr** [Watts-Lab/atlas#75]
In the current version of the platform, we wait for the result of a call to finish before returning a response to the frontend. This is bad design and we should immediately return a response with task.id for the frontend to track the status of the paper and retrieve the data after it is done. This would also enable us to run for multiple papers and update the results and show them as they finish.

**Comment by markwhiting** [comment]
I think this should be for all feature methods, which should be generically handled. 

The queuing to feature method interface needs to be where we handle the bundling of many similar feature requests into a single method request and where we handle order requirements on features. It would be nice if both of these things were entirely implicit and required no overhead by feature users. 

Some rules we might think about are things like: 
1. Root parent-level features are always sampled first.
2. Features with no sub-features are done before those with them. 
3. Features with common parents (e.g., condition) + common methods (e.g., GPT4o) are pooled automatically.

As an aside, we may need feature requirements outside of parents. I don't know if we will, so let's not engineer for it yet. But let's keep in mind that we might need to adjust for that case at some point.
